# config/_default/languages.en.toml

title = "Kedar Joyner"

[author]
name = "Hello, I'm Kedar Joyner 👋"
image = "img/author.jpg"
headline = "My name rhymes with cheddar. New site coming soon!"
bio = "A little bit about me"
links = [
  { instagram = "https://www.instagram.com/kedarjoynerdraws" }
]
