# config/_default/languages.en.toml

title = "Kedar Joyner"
description = "A UX/UI designer with a knack for programming."

[author]
name = "Kedar Joyner 💕"
image = "img/author.jpg"
headline = ""
bio = "UX/UI Designer with a knack for programming"
links = [
  { instagram = "https://www.instagram.com/kedarjoynerdraws" }
]
