[[main]]
  name = "Instagram"
  url = "https://www.instagram.com/kedarjoynerdraws"
  # pageRef = "posts"
  # weight = 10
   [main.params]
    icon = "instagram"
    showName = false
    target = "_blank"

[[main]]
  name = ""
  pageRef = "categories"
  weight = 20

[[main]]
  name = ""
  pageRef = "tags"
  weight = 30

[[main]]
  identifier = ""
  weight = 99
  [main.params]
    action = ""