[[main]]
  name = ""
  pageRef = "posts"
  weight = 10

[[main]]
  name = ""
  pageRef = "categories"
  weight = 20

[[main]]
  name = ""
  pageRef = "tags"
  weight = 30

[[main]]
  identifier = ""
  weight = 99
  [main.params]
    action = ""